In [1]:
# Locate data directory and read in data files
import os
from pathlib import Path
import pandas as pd

current_dir = Path(os.getcwd()).parent
data_dir = current_dir / 'data'
data_dir = data_dir.resolve()

try:
    final_crosswalk_df = pd.read_csv(data_dir / 'final_crosswalk.csv')
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    print(f"Please make sure your CSV files are in the directory: {data_dir}")
    exit()

In [7]:
final_crosswalk_df[final_crosswalk_df["cik"].duplicated(keep = False) & final_crosswalk_df["FED_RSSD"].notna()]

,standardized_names,aliases,cik,FED_RSSD,sources,matching_type,fuzzy_matching_score
749,bb t financial,"BB&T FINANCIAL CORP|BB&T FUNDS|BB&T Financial,...",13839,2689463.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
3278,united california bank,BANK OF THE WEST|SANWA BANK CALIFORNIA|UNITED ...,59951,438368.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
3517,mellon bank,MELLON BANK CORP|MELLON FINANCIAL CORP|Mellon ...,64782,825904.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
7002,lasalle national bank,LASALLE BANK N A|LASALLE NATIONAL BANK|LaSalle...,275635,79837.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
8011,morgan guaranty trust new york,MORGAN GUARANTY TRUST CO OF NEW YORK ET AL|MOR...,315241,161415.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
...,...,...,...,...,...,...,...
569567,darien rowayton bank,DARIEN ROWAYTON BANK|DR BANK|LAUREL ROAD BANK|...,1643675,3428258.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
585800,coconut grove bank,COCONUT GROVE BANK|GROVE BANK & TRUST|Coconut ...,1662212,648130.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
617417,pacific premier bank,OPUS BANK|PACIFIC PREMIER BANK|OPUS BANK|Pacif...,1697463,431172.0,"cik,compustat,fdic","cik_id_match,,standardized_name_matching",[]
660745,bank first national,BANK FIRST CORP|BANK FIRST NATIONAL CORP|BANK ...,1746109,594947.0,"cik,compustat,fdic","cik_id_match,,standardized_name_matching",[]
671433,ameriprise national trust bank,"AMERIPRISE BANK, FSB|AMERIPRISE NATIONAL TRUST...",1758825,3470239.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]

In [11]:
final_crosswalk_df[final_crosswalk_df['cik'] == 819975]

,standardized_names,aliases,cik,FED_RSSD,sources,matching_type,fuzzy_matching_score
22843,bank one delaware national|cbc national bank,BANK ONE DELAWARE NATIONAL ASSOCIATION|CHASE...,819975,2855914.0,"cik,fdic","cik_id_match,fuzzy_matching",[94.11764705882354]
22844,fcc national bank|cbc national bank,BANK ONE DELAWARE NATIONAL ASSOCIATION|CHASE...,819975,2855914.0,"cik,fdic","cik_id_match,fuzzy_matching",[94.11764705882354]
22845,first usa bank national|cbc national bank,BANK ONE DELAWARE NATIONAL ASSOCIATION|CHASE...,819975,2855914.0,"cik,fdic","cik_id_match,fuzzy_matching",[94.11764705882354]
861406,chase bank usa|chase manhattan bank usa,BANK ONE DELAWARE NATIONAL ASSOCIATION|CHASE...,819975,NaN,cik,cik_id_match,NaN

In [3]:
final_crosswalk_df[final_crosswalk_df["FED_RSSD"].notna()]

,standardized_names,aliases,cik,FED_RSSD,sources,matching_type,fuzzy_matching_score
749,bb t financial,"BB&T FINANCIAL CORP|BB&T FUNDS|BB&T Financial,...",13839,2689463.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
1965,fifth third bank|jgb bank,"FIFTH THIRD BANK, NATIONAL ASSOCIATION|FIFTH T...",35528,838632.0,"cik,fdic","cik_id_match,fuzzy_matching",[92.85714285714286]
3278,united california bank,BANK OF THE WEST|SANWA BANK CALIFORNIA|UNITED ...,59951,438368.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
3517,mellon bank,MELLON BANK CORP|MELLON FINANCIAL CORP|Mellon ...,64782,825904.0,"cik,fdic","cik_id_match,,standardized_name_matching",[]
3930,bank new england|new england bank,BANK OF NEW ENGLAND CORP|NEW ENGLAND BANK,71322,2858205.0,"cik,fdic",fuzzy_matching,[100.0]
...,...,...,...,...,...,...,...
754201,choice financial group,"CHOICE FINANCIAL GROUP, LLC|Choice Financial G...",1857130,826956.0,"cik,fdic",NaN,[]
761051,heartland bank trust,HEARTLAND BANK & TRUST CO|Heartland Bank and T...,1866040,426534.0,"cik,fdic",NaN,[]
765521,morgan stanley bank,"MORGAN STANLEY BANK, N.A.|Morgan Stanley Bank,...",1871769,1456501.0,"cik,fdic",NaN,[]
791298,midwest heritage bank,"MIDWEST HERITAGE BANK, FSB|Midwest Heritage Ba...",1906805,203043.0,"cik,fdic",NaN,[]
792809,merchants bank indiana,MERCHANTS BANK OF INDIANA|Merchants Bank of In...,1908863,963945.0,"cik,fdic",NaN,[]