In [1]:
# Locate data directory and read in data files
import os
from pathlib import Path
import pandas as pd
from helper_functions import *

current_dir = Path(os.getcwd()).parent
data_dir = current_dir / 'data'
data_dir = data_dir.resolve()

try:
    final_crosswalk_df = pd.read_csv(data_dir / 'final_crosswalk.csv')
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    print(f"Please make sure your CSV files are in the directory: {data_dir}")
    exit()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/stevenkang/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/var/folders/9p/px6hv6w54h9f61mj90xkdjxm0000gn/T/ipykernel_34744/3343434963.py:12: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  final_crosswalk_df = pd.read_csv(data_dir / 'final_crosswalk.csv')

In [2]:
final_crosswalk_df[final_crosswalk_df["cik"].duplicated(keep = False)]

,aliases,standardized_names,cik,FED_RSSD,ticker,naics,sources,matching_type,fuzzy_matching_score,ineligible_name_matching
716178,American Savings and Loan Association|McKinley...,american savings loan|mckinley savings loan|un...,NaN,0.0,NaN,NaN,fdic,FED_RSSD_match,NaN,False
716179,1st Atlantic Bank,1st atlantic bank,NaN,28.0,NaN,NaN,fdic,NaN,NaN,False
716180,Bank of Hancock County,bank hancock,NaN,37.0,NaN,NaN,fdic,NaN,NaN,False
716181,Republic Bank,republic bank,NaN,46.0,NaN,NaN,fdic,NaN,NaN,False
716182,State Bank of Littlefork,bank littlefork,NaN,55.0,NaN,NaN,fdic,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...
740599,Bank of Bird-in-Hand,bank bird--hand,NaN,4536084.0,NaN,NaN,fdic,NaN,NaN,False
740600,New Traditions Bank,new traditions bank,NaN,4569167.0,NaN,NaN,fdic,NaN,NaN,False
740601,Primary Bank,primary bank,NaN,4845861.0,NaN,NaN,fdic,NaN,NaN,False
740602,International Bank of Commerce,international bank,NaN,5050028.0,NaN,NaN,fdic,NaN,NaN,False
740603,Blue Gate Bank,blue gate bank,NaN,5086072.0,NaN,NaN,fdic,NaN,NaN,False

In [3]:
final_crosswalk_df[final_crosswalk_df["standardized_names"].isna()]

,aliases,standardized_names,cik,FED_RSSD,ticker,naics,sources,matching_type,fuzzy_matching_score,ineligible_name_matching
754094,FOUNDATION COMMERCE CORP,NaN,1171552.0,NaN,NaN,NaN,cik,NaN,NaN,True
754255,LLC,NaN,1173062.0,NaN,NaN,NaN,cik,NaN,NaN,True
755266,ACADEMY LTD,NaN,1186365.0,NaN,NaN,NaN,cik,NaN,NaN,True
765581,UNIVERSITY MEDICAL CENTER LLC,NaN,1326680.0,NaN,NaN,NaN,cik,NaN,NaN,True
776979,$ LLC,NaN,1427189.0,NaN,NaN,NaN,cik,NaN,NaN,True
804607,"INSTITUTE, P.B.C.",NaN,1771320.0,NaN,NaN,NaN,cik,NaN,NaN,True

In [4]:
fuzzy_rows = final_crosswalk_df[
    (final_crosswalk_df['fuzzy_matching_score'].str.len() > 0) & 
    (final_crosswalk_df['fuzzy_matching_score'].astype(str) != '[]')
]
fuzzy_rows

,aliases,standardized_names,cik,FED_RSSD,ticker,naics,sources,matching_type,fuzzy_matching_score,ineligible_name_matching
108,AMERICAN EXPRESS CO|American Express Co|Americ...,american express|american express bank,4962.0,2966306.0,AXP,522210.0,"cik,compustat,sec,fdic","cik_id_match,fuzzy_matching",[91.42857142857143],False
1810,BANK OF NEW ENGLAND CORP|NEW ENGLAND BANK,bank new england|new england bank,71322.0,2858205.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
3130,SOUTHERN UNION CO|Southern Union Co|Union Plan...,southern union|union planters bank southern mi...,203248.0,570736.0,SUG,221210.0,"cik,compustat,sec,fdic","cik_id_match,fuzzy_matching",[90.3225806451613],False
5716,FOOTHILL INDEPENDENT BANCORP|Foothill Independ...,foothill independent bancorp|foothill independ...,718903.0,181169.0,FOOT,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[90.56603773584905],False
7703,FIRST COMMUNITY FINANCIAL CORP|First Community...,first community financial|first community fina...,763293.0,3809446.0,FMFP,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[90.9090909090909],False
12894,US BANK NATIONAL ASSOCIATION|ANCHOR BANK FARMI...,us bank national|anchor bank farmington,830013.0,939959.0,NaN,NaN,"cik,fdic",fuzzy_matching,[94.33962264150944],False
13055,UNITED NATIONAL BANCORP|United National Bancor...,united national bancorp|national united,831959.0,322056.0,UNBJ,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
14808,MFC FIRST NATIONAL BANK|FIRST NATIONAL BANK OF...,mfc first national bank|first national bank no...,853470.0,330248.0,NaN,NaN,"cik,fdic",fuzzy_matching,[90.47619047619048],False
17228,COMMUNITY FIRST BANK ...,community first bank ta|community first bank h...,878306.0,273840.0,NaN,NaN,"cik,fdic",fuzzy_matching,[90.9090909090909],False
21176,PEOPLES FIRST NATIONAL BANK & TRUST CO OF PADU...,peoples first national bank trust paducah|peop...,903511.0,795052.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
21833,TOWN & COUNTRY TRUST|Town & Country Trust|Town...,country trust|country bank trust,906110.0,692946.0,TCT,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
31202,CITIZENS FIRST FINANCIAL CORP|Citizens First F...,citizens first financial|citizens first financ...,1006265.0,891552.0,CFSB,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[90.56603773584905],False
36820,GOVERNOR & CO OF THE BANK OF IRELAND|Governor ...,governor bank ireland|ireland bank,1022575.0,428462.0,IRE,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
36906,FIRST COMMUNITY BANK /TN|COMMUNITY FIRST BANK ...,first community bank tn|community first bank h...,1022792.0,273840.0,NaN,NaN,"cik,fdic",fuzzy_matching,[90.9090909090909],False
52378,WASHINGTON BANKING CO|Washington Banking Co|Wa...,washington banking|washington loan banking,1058690.0,169934.0,WBCO,522110.0,"cik,compustat,sec,fdic","cik_id_match,fuzzy_matching",[92.3076923076923],False
65761,BANK ONE CAPITAL I|Bank One Capital I|Capital ...,bank one capital i|capital one bank usa,1088800.0,2253891.0,NXMR,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[94.11764705882354],False
69061,FIRST COMMUNITY BANK NA|COMMUNITY FIRST BANK O...,first community bank na|community first bank h...,1096921.0,273840.0,NaN,NaN,"cik,fdic",fuzzy_matching,[93.02325581395348],False
75027,LAFAYETTE COMMUNITY BANCORP|LAFAYETTE COMMUNIT...,lafayette community bancorp|lafayette communit...,1111230.0,2911128.0,NaN,NaN,"cik,fdic",fuzzy_matching,[90.19607843137254],False
80383,BANK ONE CAPITAL VI|BANK VI,bank one capital vi|bank vi,1124817.0,804758.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
94592,UM INVESTMENT TRUST|Um Investment Trust|Boston...,um investment trust|boston trust investment ma...,1162780.0,972406.0,UMIT,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[91.42857142857143],False
100281,FLORIDA COMMUNITY BANKS INC|Florida Community ...,florida community banks|floridian community bank,1170902.0,3176812.0,FLRB,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[91.2280701754386],False
199458,COMMUNITY TRUST BANK INC|COMMUNITY TRUST BANK ...,community trust bank|community trust bank texas,1291629.0,3717288.0,NaN,NaN,"cik,fdic",fuzzy_matching,[90.9090909090909],False
208366,PACIFIC COAST NATIONAL BANCORP|Pacific Coast N...,pacific coast national bancorp|pacific coast n...,1302502.0,3338843.0,PCST,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[91.2280701754386],False
219149,TEXAS COMMUNITY BANK|COMMUNITY TRUST BANK OF T...,texas community bank|community trust bank texas,1315481.0,3717288.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
236741,EVERGREEN INTERNATIONAL BALANCED INCOME FUND|E...,evergreen international balanced income fund|e...,1336593.0,3598218.0,EBI,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[90.19607843137254],False
279469,"PIEDMONT COMMUNITY BANK GROUP, INC.|Piedmont C...",piedmont community bank group|piedmont communi...,1388337.0,3128914.0,PCBN,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
290412,"FIRST FINANCIAL NORTHWEST, INC.|FIRST FINANCIA...",first financial northwest|first financial nort...,1401564.0,768074.0,FFNW,522110.0,"cik,compustat,sec,fdic","cik_id_match,fuzzy_matching",[92.5925925925926],False
290419,"BEACON FEDERAL BANCORP, INC.|BEACON FEDERAL BA...",beacon bancorp|beacon,1401573.0,498184.0,BFED,522120.0,"cik,compustat,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
318162,AB&T FINANCIAL CORP|Ab&t Financial Corp|AB&T,ab t financial|ab t,1435161.0,2775151.0,ABTO,NaN,"cik,sec,fdic","cik_id_match,fuzzy_matching",[100.0],False
343661,M|C ACQUISITION CORP.|F & M Bank-Pulaski,m c acquisition|f m bank-pulaski,1467416.0,56146.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
517666,SOUTHWEST BANK|SOUTHWEST BANK OF PHOENIX,southwest bank|southwest bank phoenix,1682358.0,2959700.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
584089,"VWP EVB 200 INVESTOR, LLC|EVB",vwp evb 200 investor|evb,1762093.0,790721.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False
607430,TCF NATIONAL BANK|TCF NATIONAL BANK ILLINOIS,tcf national bank|tcf national bank illinois,1790153.0,646976.0,NaN,NaN,"cik,fdic",fuzzy_matching,[100.0],False

# Final crosswalk cleanup for package use

In [27]:
final_crosswalk_df

,aliases,standardized_names,cik,FED_RSSD,ticker,naics,sources,matching_type,fuzzy_matching_score,ineligible_name_matching
0,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...,defined asset funds municipal invt tr fd new y...,3.0,NaN,NaN,NaN,cik,NaN,[],False
1,CORPORATE INCOME FUND SEVENTY NINTH SHORT TERM...,corporate income fund seventy ninth short term...,13.0,NaN,NaN,NaN,cik,NaN,[],False
2,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD MON P...,defined asset funds municipal invt tr fd mon p...,14.0,NaN,NaN,NaN,cik,NaN,[],False
3,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD MON P...,defined asset funds municipal invt tr fd mon p...,17.0,NaN,NaN,NaN,cik,NaN,[],False
4,NUVEEN TAX EXEMPT UNIT TRUST SERIES 169 NATION...,nuveen tax exempt unit trust series 169 nation...,18.0,NaN,NaN,NaN,cik,NaN,[],False
...,...,...,...,...,...,...,...,...,...,...
830665,FREMONT GOLD CORP|ROTHCHILD COMPANIES INC,fremont gold|rothchild companies,99680.0,NaN,NaN,NaN,cik,cik_id_match,NaN,True
830666,AUDITS & SURVEYS WORLDWIDE INC|TRIANGLE CORP,audits surveys worldwide|triangle,99703.0,NaN,NaN,NaN,cik,cik_id_match,NaN,True
830667,TRINITY CAPITAL CORP,trinity capital,99771.0,NaN,NaN,NaN,cik,NaN,NaN,True
830668,TRIPP & CO INC ...,tripp bd|tripp,99817.0,NaN,NaN,NaN,cik,cik_id_match,NaN,True
830669,TRITON ENERGY CORP,triton energy,99830.0,NaN,NaN,NaN,cik,NaN,NaN,True

In [29]:
final_crosswalk_df.drop(columns = ['standardized_names', 'matching_type', 'fuzzy_matching_score', 'ineligible_name_matching'])

,aliases,cik,FED_RSSD,ticker,naics,sources
0,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...,3.0,NaN,NaN,NaN,cik
1,CORPORATE INCOME FUND SEVENTY NINTH SHORT TERM...,13.0,NaN,NaN,NaN,cik
2,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD MON P...,14.0,NaN,NaN,NaN,cik
3,DEFINED ASSET FUNDS MUNICIPAL INVT TR FD MON P...,17.0,NaN,NaN,NaN,cik
4,NUVEEN TAX EXEMPT UNIT TRUST SERIES 169 NATION...,18.0,NaN,NaN,NaN,cik
...,...,...,...,...,...,...
830665,FREMONT GOLD CORP|ROTHCHILD COMPANIES INC,99680.0,NaN,NaN,NaN,cik
830666,AUDITS & SURVEYS WORLDWIDE INC|TRIANGLE CORP,99703.0,NaN,NaN,NaN,cik
830667,TRINITY CAPITAL CORP,99771.0,NaN,NaN,NaN,cik
830668,TRIPP & CO INC ...,99817.0,NaN,NaN,NaN,cik
830669,TRITON ENERGY CORP,99830.0,NaN,NaN,NaN,cik

EDA for tier 1 matches from the python regextable script

In [5]:
try:
    tier1_matches = pd.read_csv(data_dir / 'matches_stage1_CIK.csv')
except FileNotFoundError as e:
    print(f"Error loading file: {e}")
    print(f"Please make sure your CSV files are in the directory: {data_dir}")
    exit()

In [ ]:
tier1_matches['unique_id'] = tier1_matches['unique_id'].astype(str).str.replace('CIK-', '', regex=False)
tier1_matches['unique_id'] = tier1_matches['unique_id'].astype(int)

In [ ]:
overlap_df = final_crosswalk_df.merge(tier1_matches, left_on='cik', right_on='unique_id', how='inner')

In [17]:
# Use a right merge to keep everything in df2
combined = final_crosswalk_df.merge(tier1_matches, left_on='cik', right_on='unique_id', how='right', indicator=True)

# Filter for 'right_only' to find what's missing from the left
only_in_right = combined[combined['_merge'] == 'right_only']